Update DPC++ to the newest compatible version
celerity/celerity-runtime pull request #150
Opened 2022-10-08 07:33 UTC by fknorr

After being stuck on [a bug](https://github.com/celerity/celerity-runtime/actions/runs/2924269790/jobs/4663659961) for some time, recent versions of DPC++ are compatible with Celerity again. This PR bumps the minimum required version to a commit from the beginning of October and adjusts the necessary workarounds. This also enables subgroup support in Celerity when compiling against DPC++.

The CI temporarily targets `dpcpp:HEAD` to show compatibility. I willl re-tag `latest` and revert this as soon as the PR is accepted.

2022-10-11 10:33 UTC, psalz requested changes
Thanks! L(mostly)GTM

2022-10-11 10:33 UTC, psalz commented on docs/platform-support.md
> +| DPC++      | [`3fd08509`](https://github.com/intel/llvm/commit/7735139b)                    | Ubuntu 20.04 | Debug          |
```suggestion
| DPC++      | [`3fd08509`](https://github.com/intel/llvm/commit/3fd08509)                    | Ubuntu 20.04 | Debug          |
```

2022-10-11 10:33 UTC, psalz commented on include/accessor.h
>  #pragma GCC diagnostic ignored "-Wdeprecated-declarations" // target::gobal_buffer is now target::device, but only for very recent versions of DPC++
Sounds like we can get rid of this pragma then?

2022-10-11 10:33 UTC, psalz commented on test/sycl_tests.cc
>  #pragma GCC diagnostic ignored "-Wdeprecated-declarations" // target::gobal_buffer is now target::device, but only for very recent versions of DPC++
Same here

2022-10-18 12:32 UTC, BlackMark29A requested changes
Looks good to me, for the most part. I also tested it on Windows, which surfaced a change in DPC++, namely that the sycl library is now called `sycl6`, because why not.

With this change it also works on Windows:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 61626d5..8eb763a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -236,8 +236,8 @@ target_include_directories(celerity_runtime PUBLIC
 # because they are not ABI compatible.
 if(WIN32 AND CELERITY_SYCL_IMPL STREQUAL "DPC++")
   set(SYCL_LIB
-    $<$<CONFIG:Debug>:sycld>
-    $<$<CONFIG:Release>:sycl>
+    $<$<CONFIG:Debug>:sycl6d>
+    $<$<CONFIG:Release>:sycl6>
   )
 endif()
```

2022-11-14 13:30 UTC, psalz approved these changes

2022-11-14 13:49 UTC, BlackMark29A approved these changes
LGTM.

2023-02-17 14:12 UTC, merged