Make subrange/chunk conversions explicit; report kernel / range mapper dimensionality mismatches
celerity/celerity-runtime pull request #39
Opened 2021-07-27 17:38 UTC by fknorr

Previously, `subrange` and `chunk` were implicitly convertible between dimensions.
This allowed mismatches between kernel dimensionality and the chunk dimensionality accepted by range mappers to go unnoticed.
Casts are now explicit via `detail::subrange_cast` and `detail::chunk_cast`.
We attempt to report range mapper signature mismatches aside from dimensionality at compile time, and fail on dimensionality mismatch at runtime.

2021-07-27 18:08 UTC, fknorr commented
These stricter checks now require us to specify `KernelDim = 1` on all accessors used by master-node host tasks, since those internally invoke range mappers with a unit-sized 1-dimensional chunk.

This is somewhat unergonomic because
1. it is not obvious that a master-node task does not have `KernelDim == 0` and
2. both `access::fixed` and `access::all` always have conceptually defined semantics even without knowledge of the kernel dimensionality.

Ideally, fixed range mappers whould have generic call operators, but this is currently impossible because we require a non-templated `operator()` to deduce the range mapper result dimensionality. We should probably re-visit this implementation decision.

2021-07-28 14:14 UTC, fknorr commented
I have modified range mapper integration to accept generic mapper functions and mapper function objects with a generic or overloaded `operator()`. Range mappers now do not necessarily need to know about kernel or buffer dimensionality any more.

As a consequence, template parameters to `celerity::access::all` and `celerity::access::one_to_one` are no longer required, and `celerity::access::fixed` only needs the buffer dimensionality, not the kernel's. These built-in mappers still optionally accept dimensionality parameters for backwards compatibility, but will issue a deprecation warning.

This change is in part possible due to the optional `buffer_size` argument to range mappers which was introduced with host tasks and the `equal_split` range mapper. This parameter allows the range mapper to receive the buffer dimensionality, which makes generic `all` or `fixed` mappers straightforward.

2021-08-02 16:01 UTC, psalz requested changes
This looks like a very good change! I've just added some minor remarks.

2021-08-02 17:05 UTC, fknorr commented on include/range_mapper.h
> +	fixed(subrange<BufferDims>) -> fixed<BufferDims>;
This seems to be fixed for some clang-format version > 12.0.0

2021-08-02 17:06 UTC, fknorr commented on include/ranges.h
> +	chunk<Dims> chunk_cast(chunk<OtherDims> other) {
I used this opportunity to pass more things by const-ref where possible in the context of this PR

2021-08-02 17:08 UTC, fknorr commented on include/accessor.h
> +			const auto sr = live_cgh.apply_range_mapper<Dims>(rmfn, buff.get_range());
Yes, this is possible because we have been passing the buffer size to range mappers since host tasks were introduced.

2021-08-02 17:09 UTC, fknorr commented on include/ranges.h
> +	friend bool operator==(const chunk& lhs, const chunk& rhs) {
I added them for a `==` check within a unit test but ended up not needing them - I'll keep them in regardless, this is the obvious definition.

2021-08-03 08:20 UTC, psalz approved these changes

2021-08-03 08:20 UTC, psalz commented
LGTM!

2021-08-03 08:29 UTC, merged