Support DPC++ as a SYCL implementation
celerity/celerity-runtime pull request #45
Opened 2021-09-03 19:39 UTC by fknorr

Adds support for DPC++ as a SYCL implementation on Intel platforms.

The patch requires few workarounds but a rather visible surface API change: Accessor constructor tags (e.g. `read_only_host_task` and `no_init`) now have to be specified relative to the `celerity` namespace instead of `cl::sycl` as it was previously.

The changes for DPC++ integration triggered two unrelated bugs in the ComputeCpp compiler, both for which workarounds were introduced.

CMake will now able to auto-detect which SYCL implementation is in use.

2021-09-05 07:08 UTC, PeterTh approved these changes
I like the `constexpr_false` addition.
LGTM overall.

2021-09-06 11:26 UTC, psalz requested changes
Awesome! I've added a few minor notes.

Also, I found a few places where the documentation still requires updating:
- `host-tasks.md`: Change to `celerity::access::target`
- `pitfalls.md`: ^
- `tutorial.md` ^
- `installation.md`: Consider explicitly mentioning `CELERITY_SYCL_IMPL` here..?

2021-09-06 13:18 UTC, fknorr commented on CMakeLists.txt
> +try_compile(CXX_COMPILER_IS_DPCPP "${PROJECT_BINARY_DIR}/detect_dpcpp"
Fixed. Also, `option` was not the right command here, that's only for booleans - replace with `set(... CACHE ...)`.

2021-09-06 13:19 UTC, fknorr commented on cmake/FindComputeCpp.cmake
> +find_package(OpenCL)
Done.

2021-09-06 13:19 UTC, fknorr commented on include/accessor.h
> +template <typename DataT, int Dims, access_mode Mode, celerity::target Target>
I removed unnecessary qualifications for consistency.

2021-09-06 13:19 UTC, fknorr commented on include/accessor.h
>  		// always fails to compile. Hence we use a templated type so that it only produces a compile error when the ctr is loaded.
Done.

2021-09-06 13:20 UTC, fknorr commented on include/sycl_wrappers.h
> +	host_task = static_cast<std::underlying_type_t<cl::sycl::access::target>>(cl::sycl::access::target::host_buffer),
Actually the relationship between `celerity::target` and `cl::sycl::target` is not necessary at all, this is now just a simple enum.

2021-09-06 13:21 UTC, fknorr commented on include/sycl_wrappers.h
> +inline const property::no_init no_init;
No, because `property::no_init` does not have a constexpr default ctor.

2021-09-06 13:21 UTC, fknorr commented on CMakeLists.txt
> +if (CELEIRTY_SYCL_IMPL STREQUAL "DPC++")
Fixed.

2021-09-06 14:01 UTC, psalz commented on CMakeLists.txt
> +try_compile(CXX_COMPILER_IS_DPCPP "${PROJECT_BINARY_DIR}/detect_dpcpp"
Ah, good catch!

2021-09-06 14:05 UTC, psalz commented on include/sycl_wrappers.h
> +inline const property::no_init no_init;
Hm, okay. According to the 2020 spec (4.7.6.4) it should, but we can fix that once the implementations catch up.

2021-09-06 14:06 UTC, psalz approved these changes

2021-09-08 07:31 UTC, facuMH approved these changes
LGTM

2021-09-08 08:53 UTC, merged