Add support for nd-range kernels and local memory
celerity/celerity-runtime pull request #49
Opened 2021-10-09 12:10 UTC by fknorr

With this patch, all `parallel_for` overloads allow specifying the work-group size by accepting an `nd_range` parameter. The work-group size is respected in the split, which receives a non-1 _granularity_ parameter. Kernels in these invocations will receive a `celerity::nd_item`.

`celerity::nd_item` and `celerity::group` provide equivalent functionality to their `sycl::` counterparts. Celerity exposes group-cooperative functions such as `celerity::reduce_over_group` as long as they are present in the SYCL implementation. We guarantee that at least `celerity::group_barrier` is present, which is a minimum requirement for any meaningful use of local memory.

Capturing a `celerity::local_accessor` allocates local memory to a kernel. Support for this is unfortunately limited to DPC++ (using an ugly hack for default-constructing the corresponding SYCL accessor) and a yet-to-be-released version of hipSYCL (cf. illuhad/hipSYCL#639). The `mat_mul` example has been updated to use local memory tiling when available.

To maintain our support for a wide variety of SYCL implementations and versions, the Celerity CMake project now detects SYCL features at configuration time, exposing three feature-detection macros (both in CMake as `ON`/`OFF` as well as in C++ defined to either `0` or `1`):

- `CELERITY_FEATURE_LOCAL_ACCESSOR` if Celerity can support local accessors with the given SYCL implementation
- `CELERITY_FEATURE_SIMPLE_SCALAR_REDUCTIONS` for the limited reduction support provided by DPC++
- `CELERITY_FEATURE_SCALAR_REDUCTIONS` for the full reduction support provided by illuhad/hipSYCL#578

2021-11-08 12:08 UTC, psalz requested changes
Thank you, a few minor notes; otherwise looks very good! Also as just discussed in person, please remove the relevant section from our "Issues & Limitations" documentation!

2021-11-08 15:10 UTC, fknorr commented on include/sycl_wrappers.h
> +enum class memory_scope { work_item, sub_group, work_group, device };
Done, with the exception of ComputeCpp which does not have this enum.

2021-11-08 15:11 UTC, fknorr commented on include/item.h
> +	// We capture SYCL `item` instead of `group` to provide celerity::group_barrier based on SYCL 1.2.1 nd_item.barrier()
Done.

2021-11-11 10:53 UTC, psalz approved these changes

2021-11-11 11:17 UTC, BlackMark29A commented on CMakeLists.txt
> +  endif ()
Formatting is inconsistent with the rest of the cmake file.

2021-11-11 15:06 UTC, BlackMark29A commented on test/runtime_tests.cc
> +		CHECK_NOTHROW(q.submit([&](handler& cgh) { //
Why the `//`?

2021-11-12 08:49 UTC, BlackMark29A approved these changes

2021-11-12 11:49 UTC, merged