Silence unused variable warning
celerity/celerity-runtime pull request #83
Opened 2022-02-01 15:02 UTC by psalz

Also I've changed the check for `GetProcessAffinityMask` to compare against `0`. Even though the [signature](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprocessaffinitymask) says `BOOL`, the description talks about zero and non-zero return values, and I found a check `assert(error != false)` to be confusing.

2022-02-01 15:41 UTC, fknorr requested changes

2022-02-01 15:41 UTC, fknorr commented on src/platform_specific/affinity.unix.cc
> +		(void)affinity_error;
I would like a `[[maybe_unused]]` on the declaration itself better (same below).

2022-02-01 15:53 UTC, BlackMark29A commented
> I found a check `assert(error != false)` to be confusing

I agree, but I think that's the fault of a badly named variable. The variable is called `error`, and is semantically a `bool`, but if the value evaluates to `true` it is the non-error case. So I'd say that's a misnomer.

2022-02-04 17:21 UTC, psalz commented
Done. Due to a lack of creativity on my part, I've renamed the return values to `ret`.

2022-02-07 18:47 UTC, fknorr approved these changes
LGTM!

2022-02-08 08:21 UTC, merged