Reduce local range size to improve device compatibility
celerity/celerity-runtime pull request #91
Opened 2022-02-14 14:51 UTC by BlackMark29A

Previous local range size of `{16, 16}` would lead to a `PI_OUT_OF_RESOURCES` exception being thrown on an Intel i7-4790K. Reducing it to `{8, 8}` fixes the problem.

2022-02-14 14:59 UTC, fknorr requested changes
It's fine to adjust the local size here, but we should test the same APIs regardless.

2022-02-14 15:03 UTC, BlackMark29A commented on test/runtime_tests.cc
> +				group_broadcast(item.get_group(), 42, {1, 2});
Done.

2022-02-14 15:11 UTC, fknorr approved these changes
LGTM

2022-02-15 08:27 UTC, psalz requested changes
Since now all three assertions use a local size of 64, the comment above should probably be adjusted to say
> not all devices support work groups with > 64 elements

And in general, while that statement is not wrong, the SYCL spec doesn't actually mandate *any* minimum work group size. So I'm wondering whether we should lower that number further, or if we should check `info::device::max_work_group_size` and just skip the test if it's lower than what we need.

2022-02-15 14:10 UTC, BlackMark29A commented
I didn't know `info::device::max_work_group_size` was a thing. That is indeed very useful here. Is there a reason why we can't just do `std::min(64, info::device::max_work_group_size)` and use that as the local size? That way we wouldn't have to skip the test.

2022-02-15 14:24 UTC, PeterTh commented
I'm not sure what exactly `max_work_group_size` does, but I recall that a similar thing in OpenCL only reported the HW maximum *in absence of anything going on in the Kernel*. I.e. you could use the reported number but still fail for any given Kernel if e.g. you go beyond the register file or local mem limit.

2022-02-15 14:45 UTC, PeterTh commented
Very unlikely, but since it came up I wanted to note that you can't always rely on actually being able to execute a kernel just because you stay below these limits.

2022-02-15 17:05 UTC, psalz commented
> I didn't know `info::device::max_work_group_size` was a thing. That is indeed very useful here. Is there a reason why we can't just do `std::min(64, info::device::max_work_group_size)` and use that as the local size? That way we wouldn't have to skip the test.

Sounds good, if all implementations support that query.

2022-02-16 07:24 UTC, fknorr commented
Keep in mind that this is not the only usage of explicit work group sizes in our tests and examples. Others include the matmul example, reduction-related runtime tests and a test on `nd_item` in `distr_tests`.

@BlackMark29A can you test whether the `distr_test` "nd_item and group return correct execution space geometry" works on your hardware? It requests a WG size of 3·5·11 in the 3D case, which is probably too large. Unlike other `distr_tests` this test doesn't need mpirun if you run it using `./distr_tests [item]`.

I suggest we don't overengineer this and just assume that all hardware supports at least WG size 64 until we are proven wrong. Maybe add a small comment in all places that assume minimum WG sizes, so the reason for false-negative test results will be even more obvious.

2022-02-16 11:24 UTC, BlackMark29A commented
> @BlackMark29A can you test whether the `distr_test` "nd_item and group return correct execution space geometry" works on your hardware? It requests a WG size of 3·5·11 in the 3D case, which is probably too large. Unlike other `distr_tests` this test doesn't need mpirun if you run it using `./distr_tests [item]`.

Interestingly, this test passes without any problems on my hardware.

> I suggest we don't overengineer this and just assume that all hardware supports at least WG size 64 until we are proven wrong. Maybe add a small comment in all places that assume minimum WG sizes, so the reason for false-negative test results will be even more obvious.

I didn't know there were so many places that would need changing. So yes, I agree, no need to overengineer this. I will add comments where appropriate, and also test everything on my hardware.

2022-02-17 09:47 UTC, PeterTh approved these changes
LGTM

2022-02-17 09:48 UTC, merged