Remove printf from runtime test
celerity/celerity-runtime pull request #95
Opened 2022-02-23 12:13 UTC by BlackMark29A

Currently there is one runtime test which makes use of `printf`, this is not necessary, however, and the same functionality can be better implemented using the `CAPTURE` feature of catch2.  

This PR eliminates the `printf` and slightly simplifies the test.

2022-02-23 12:48 UTC, fknorr approved these changes

2022-02-23 15:53 UTC, psalz requested changes

2022-02-23 15:53 UTC, psalz commented on test/runtime_tests.cc
> -			bool valid = true;
The reason it was done this way was to avoid counting each iteration of the loop as a separate assertion (reported by Catch2), because those numbers (IMO) quickly become meaningless. This is a problem we currently have with the `distr_tests`, where we have 58130 assertions in 5 test cases.

A compromise might look something like this:
```c++
const auto expected = source_id[0] * 10000 + source_id[1] * 100 + source_id[2];
const auto received = target_buffer[get_linear_index(target_range, id)];
CAPTURE(id, source_id, expected, received);
if(received != expected) {
  FAIL();
}
```

Of course we then don't count any assertion for this test case.

2022-02-24 11:51 UTC, fknorr commented on test/runtime_tests.cc
> -			bool valid = true;
`SUCCEED()` after the loop should report one passed assertion.

On the other hand I don't fully understand why the number of passed assertions even matters. We're only interested in the absolute number of failed assertions anyway, not the ratio.

2022-02-24 12:02 UTC, BlackMark29A commented on test/runtime_tests.cc
> -			bool valid = true;
I also don't see why having `58130 assertions in 5 test cases` is actually a problem. Sure, that's a lot of assertions, but how is artificially reducing the number of assertions any more meaningful than just listing the number of individual checks that were made?

2022-03-02 09:37 UTC, psalz commented on test/runtime_tests.cc
> -			bool valid = true;
Besides the points mentioned during the last meeting (large numbers lose all meaning for humans, number of assertions depends on mostly arbitrary loop bounds), a more practical downside I found is that running tests with `-s / --success` (which I do from time to time for sanity checking) will print a metric ton of assertions, making that flag downright unusable.

I have a proof-of-concept implementation for a `REQUIRE_LOOP` macro that only logs once when called in a loop (unless it fails). Maybe this is something worth pursuing.

2022-03-02 09:50 UTC, BlackMark29A commented on test/runtime_tests.cc
> -			bool valid = true;
I like the idea of a `REQUIRE_LOOP`, so I would be in favor of pursuing that.

2022-03-10 15:13 UTC, closed without merging